version: '3'
networks:
  default:
     driver: bridge
services:  # Before Running all the services first start the sqlserver separately as docker-compose up sqlserver and then start other services
  sqlserver:  # Or run docker run --name sqlserver -e ACCEPT_EULA=Y -e SA_PASSWORD=password -p 1433:1433 -d mcr.microsoft.com/mssql/server command
    image: mcr.microsoft.com/mssql/server
    ports:
      - "1433:1433"
    restart: always
    networks:
      - default
    environment:
       - SA_PASSWORD=password
       - ACCEPT_EULA=Y
  dotnetcoreapi:
    image: dotnet-image
    ports:
      - "81:80"  
    links:
      - sqlserver
    restart: always
    networks:
      - default
    environment:
      - DBHOST=sqlserver
    depends_on:
      - sqlserver
  angular:
    image: angular-image
    ports:
      - "80:80"
    links:
      - sqlserver
      - dotnetcoreapi
    restart: always
    networks:
      - default
